version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD_DEV}
    # TZ: Asia/Seoul
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql
  express-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - .:/app
